#!/bin/sh
#
# nrpe	Start / stop nagios remote plugin execution
#
# chkconfig: 2345 95 05
# description: Start / stop nrpe (daemon mode)
# probe: true
# nrpe - Start / Stop script for nrpe
#
# Author: Andreas Ericsson
#
# Copyright (C) 2003 OP5 AB
# All rights reserved.
#
# Changelog:
# 2003-11-27 - Creation date

BINDIR=/usr/sbin
CONFIG=/etc/nrpe.conf
PROGRAM=nrpe


function check_status () {
	pids=`pidof $PROGRAM`
	if [ $? -ne 0 ]; then
		return 1
	fi
	return 0
}

if [ ! -s $CONFIG ]; then
	echo "$0: can't read config file $config"
	exit 1
fi

if [ ! -x $BINDIR/$PROGRAM ]; then
	echo "$0: $PROGRAM is not executable"
	exit 1
fi

case "$1" in
	status)
		check_status
		if [ $? -eq 1 ]; then
			echo -e "$PROGRAM is NOT running."
			exit 0
		fi
		pids=`pidof $PROGRAM`
		echo -e "$PROGRAM is up and running with pid: $pids"
	;;
	stop)
		check_status
		if [ $? -eq 1 ]; then
			echo -e "$PROGRAM doesn't seem to be running."
			exit 0
		fi
		kill -TERM `pidof $PROGRAM`
		exit 0
	;;
	start)
		check_status
		if [ $? -eq 0 ]; then
			pids=`pidof $PROGRAM`
			echo -e "$PROGRAM is already running with pid: $pids"
			exit 0
		fi
		echo -e -n "Starting $PROGRAM in daemon mode ... "
		$BINDIR/$PROGRAM -c $CONFIG -d
		check_status
		if [ $? -eq 1 ]; then
			echo "failed!"
		else
			echo "done"
		fi
		exit 0
	;;	
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo -e "Usage: nrpe {start|stop|status|restart|reload}"
		exit 0
	;;
esac
