#!/bin/bash


while [ $# -gt 0 ]; do
	case $1 in
		-w) warning=$2;;
		-c) critical=$2;;
	esac
	shift
done


result=`vmstat 1 3 |tail -1`

r=`echo $result | awk '{ print $1 }'`

function return() {
	if [ $5 -ge $2 ]; then
		echo "$3: CRITICAL: $4=$5| $4=$5;$1;$2;0;100"
		exit 2
	elif [ $5 -ge $1 ]; then
		echo "$3: WARNING: $4=$5|$4=$5;$1;$2;0;100"
		exit 1
	else
		echo "$3: OK: $4=$5|$4=$5;$1;$2;0;100"
		exit 0
	fi
}

return $warning $critical "Processes waiting " "r" $r
	
