#!/bin/bash
FILE="$1"
OLDDATE=`echo "$2"|tr '_' ' '`

#FILE="alert_costam.log"
#OLDDATE="Man Sep 02 22:45:35"

if [ -r "$FILE" -a -f "$FILE" ]; then
I=1;
else
echo "UNKNOWN - Unable to read $FILE";  
exit 3;
fi;
LOG=`cat $FILE|grep '...\ ...\ ..\ ..:..:..\ ....\|ORA-'|tail -10000`

LINE=`echo "$LOG"|nl|grep "$OLDDATE"|awk '{print $1}'`
if [ "x$LINE" = "x" ]; then
   LINE=0;
fi
LENGTH=`echo "$LOG"|wc -l`
TAIL=$(($LENGTH-$LINE));
#echo $TAIL;
LASTDATE=`echo "$LOG"|grep ...\ ...\ ..\ ..:..:..\ ....|tail -1`;
LOG=`echo "$LOG"|tail -$TAIL`
RESULT=`echo "$LOG"|grep -B1 'ORA-'`;
#LASTDATE=`echo "$LOG"|grep ...\ ...\ ..\ ..:..:..\ ....|tail -1`;

if [ "x$RESULT" = "x" ]; then
   echo "OK - No new ORA in alert log|$LASTDATE"
   exit 0;
fi
RESNUM=`echo "$RESULT"|grep ORA|wc -l`;
echo "CRITICAL - $RESNUM new ORA in alert log
$RESULT|$LASTDATE";
exit 2;

