#!/bin/bash

CMD="netstat --tcp";
RESULT=`$CMD`;
RESULT=`echo "$RESULT"|awk '{print $6}'|sort|grep .|uniq -c`; #do not know why cannot be inline
OUTPUT=`echo "$RESULT"|awk {'print ($2) " - " ($1)'}|tr '\n' ' '|rev|cut -b 2-|rev`

for VARIABLE in "SYN_SENT" "SYN_RECV" "ESTABLISHED" "TIME_WAIT" "LAST_ACK" "CLOSE_WAIT" "CLOSED" "CLOSING"  "FIN_WAIT1" "FIN_WAIT2"
do
#echo "$OUTPUT"|grep "$VARIABLE"|wc -l
if [ `echo "$OUTPUT"|grep "$VARIABLE"|wc -l` -eq 0 ]; then
   PERFDATA="$VARIABLE=0 $PERFDATA"
fi
done
PERFDATA=$PERFDATA`echo "$RESULT"|awk {'print ($2) "=" ($1) '}|tr '\n' ' '|rev|cut -b 2-|rev`
echo "$OUTPUT|$PERFDATA";
