#!/bin/bash
#set -x

while [ $# -gt 0 ]; do
	case $1 in
		-i) interface=$2;;
		-w) warning=$2;;
		-c) critical=$2;;
		-H|-h|--help) help; exit 3;;
	esac
	shift
done
status=""


	rx_err=`netstat -i | grep "$interface" | awk '{ print $5 }'`
	tx_err=`netstat -i | grep "$interface" | awk '{ print $9 }'`


	if [[ $rx_err -ge $critical ]] || [[ $tx_err -ge $warning ]]; then


		echo "Net Errors: rx_err=$rx_err tx_err=$tx_err | rx_err=$rx_err tx_err=$tx_err"
		exit 2
	
	elif [[ $rx_err -ge $warning ]] || [[ $tx_err -ge $warning ]]; then

		echo "Net Warnings: rx_err=$rx_err tx_err=$tx_err | rx_err=$rx_err tx_err=$tx_err"
		exit 1

	else 
		echo "Net OK rx_err=$rx_err tx_err=$tx_err| rx_err=$rx_err tx_err=$tx_err"
		exit 0
fi
